name: Node.js CI

on:
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]

jobs:
 deploy-data:
  if: ${{ github.event_name == 'push' }}
  name: deploy-data
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [18.x]

  steps:
  - uses: actions/checkout@v3
  - name: Set up Node.js environment 
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}
  - name: Setup Python environment
    uses: actions/setup-python@v4
    with:
      python-version: "3.10"
  - name: Install Poetry
    run: |
      python -m pip install --upgrade pip
      pip install poetry
  - name: Installing Serverless
    run: |
      npm install -g serverless
  - name: Update lock file
    run: |
      cd ./data
      npm install
  - name: Deploy to AWS
    run: |
      cd ./data
      npm ci
      serverless deploy --stage test --verbose --debug *
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
